# Generated by Django 3.0.5 on 2020-04-20 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('role', models.CharField(max_length=16)),
                ('clanRank', models.IntegerField()),
                ('lastSeen', models.DateTimeField()),
                ('donations', models.IntegerField()),
                ('donationsReceived', models.IntegerField()),
                ('expLevel', models.IntegerField()),
                ('clan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clash.Clan')),
            ],
        ),
        migrations.CreateModel(
            name='War',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seasonId', models.IntegerField()),
                ('createdDate', models.DateField()),
                ('clan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='clash.Clan')),
            ],
        ),
        migrations.CreateModel(
            name='WarStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberOfBattles', models.IntegerField()),
                ('battlesPlayed', models.IntegerField()),
                ('wins', models.IntegerField()),
                ('collectionDayBattlesPlayed', models.IntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clash.Player')),
                ('war', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clash.War')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='wars',
            field=models.ManyToManyField(through='clash.WarStats', to='clash.War'),
        ),
    ]
