# Generated by Django 3.0.5 on 2020-04-20 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clash', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='clanRank',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='donations',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='donationsReceived',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='expLevel',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='lastSeen',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='role',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
