# Generated by Django 3.0.5 on 2020-04-20 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clash', '0002_auto_20200420_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='trophies',
            field=models.IntegerField(default=0),
        ),
    ]
