# Generated by Django 3.0.5 on 2020-04-20 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clash', '0003_player_trophies'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='warMisses',
            field=models.IntegerField(default=0),
        ),
    ]
