# Generated by Django 3.0.5 on 2020-04-20 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clash', '0004_player_warmisses'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='warCount',
            field=models.IntegerField(default=0),
        ),
    ]
